config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :journals do
    resources :entries, only: [:new, :create, :show, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :journal
  validates :text, presence: true
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
  has_many :entries
  validates :user_id, presence: true
  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, uniqueness: true
  has_many :journals
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?, :authenticated

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def authenticated
    if logged_in?
    else
      redirect_to root_path
    end
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :authenticated

  def new
    journal = Journal.find(params[:journal_id])
    @entry = Entry.new(journal_id: journal.id)
  end

  def create
    journal = Journal.find(params[:journal_id])
    @entry = Entry.new(entry_params)
    @entry.journal_id = journal.id
    if @entry.valid?
      @entry.save
      redirect_to journal_entry_path(journal_id: journal.id, id: @entry.id)
    else
      render :new
    end
  end

  def show
    @entry = Entry.find(params[:id])
    @journal = Journal.find(params[:journal_id])
  end

  def destroy
    @journal = Journal.find(params[:journal_id])
    entry = Entry.find(params[:id])
    entry.destroy
    redirect_to journal_path(@journal)
  end

  private

  def entry_params
    params.require(:entry).permit(:title, :text)
  end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :authenticated

  def index
    @journals = Journal.where(user_id: session[:user_id])
  end

  def new
    @journal = Journal.new
  end

  def create
    @journal = Journal.new(journal_params)
    @journal.user_id = current_user.id
    if @journal.valid?
      @journal.save
      redirect_to journal_path(@journal)
    else
      render :new
    end
  end

  def show
    @journal = Journal.find(params[:id])
  end

  def destroy
    @journal = Journal.find(params[:id])
    @journal.entries.destroy_all
    @journal.destroy
    redirect_to :index
  end

  private

  def journal_params
    params.require(:journal).permit(:title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to controller: 'journals', action: 'index'
    else
      render :new
    end
  end

  def destroy
    session.delete :user_id
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.valid?
      user.save
      session[:user_id] = user.id
      redirect_to controller: 'journals', action: 'index'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entries/new.html.erb
<%= form_tag journal_entries_path do %>
  <%= label_tag :title, 'Entry Title' %>
  <%= text_field_tag 'entry[title]', nil, placeholder: 'Title' %>
  <%= label_tag :text, 'Entry Body' %><br><br>
  <%= text_area_tag 'entry[text]', nil, placeholder: 'Write entry here...', size: '100x100' %>
  <%= submit_tag %>
<% end %>

app/views/entries/show.html.erb
<h1><%= @entry.title %></h1>
<p><%= @entry.text %></p>
<%= button_to 'Back to Journal', journal_path(@journal), method: 'get' %>
<%= button_to 'Delete Entry', journal_entry_path(journal_id: @journal.id, id: @entry.id), method: 'post' %>

app/views/journals/index.html.erb
<table>
  <tr>
    <th>Journals</th>
  </tr>
  <% @journals.each do |journal| %>
    <tr>
      <td><%= journal.title %></td>
      <td><%= link_to 'view', journal_path(journal) %></td>
    </tr>
  <% end %>
</table>
<%= button_to 'Create New Journal', new_journal_path, method: 'get' %>
<%= button_to 'Logout', logout_path, method: 'post' %>

app/views/journals/new.html.erb
<h1>Create a New Journal</h1>
<%= form_for(@journal) do |f| %>
  <%= f.label :title, 'Journal Title' %>
  <%= f.text_field(:title, placeholder: 'Title', require: true) %>
  <%= f.submit %>
<% end %>

app/views/journals/show.html.erb
<table>
  <tr>
    <th><%= @journal.title %></th>
  </tr>
  <% @journal.entries.each do |entry| %>
    <tr>
      <td><%= entry.title %></td>
      <td><%= link_to 'view', journal_entry_path(journal_id: @journal.id, id: entry.id) %></td>
    </tr>
  <% end %>
</table>
<%= button_to 'Create New Journal', new_journal_path, method: 'get' %>
<%= button_to 'Add New Entry', new_journal_entry_path(@journal), method: 'get' %>
<%= button_to 'Back to Journals', journals_path, method: 'get' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateJournalMetis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_user_form.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :username, 'Create Username' %>
  <%= f.text_field(:username, placeholder: 'Username', require: true) %><br><br>
  <%= f.label :password, 'Password' %>
  <%= f.password_field(:password, placeholder: 'Password', require: true) %><br><br>
  <%= f.label :password_confirmation, 'Confirm Password' %>
  <%= f.password_field(:password_confirmation, placeholder: 'Password Confirmation', require: true) %><br><br>
  <%= f.submit %>
<% end %>

app/views/users/new.html.erb
<h1>New User</h1>
<%= render 'user_form' %>
<%= button_to 'Login', root_path, method: 'get' %>